apiVersion: v1
kind: Service
metadata:
  name: grc-api
  labels:
    app.kubernetes.io/name: grc-api
    app.kubernetes.io/part-of: grc
    app.kubernetes.io/component: backend
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: grc-api
  ports:
    - name: http
      port: 8095
      targetPort: http
      nodePort: 30095

