apiVersion: v1
kind: Secret
metadata:
  name: ai-grc-api-secret
  namespace: ai-components
type: Opaque
stringData:
  GEMINI_API_KEY: "AIzaSyDtZM50zvt0m9TBZZc0ijbgBnR7t9sqmk0"
  GOOGLE_API_KEY: "AIzaSyDtZM50zvt0m9TBZZc0ijbgBnR7t9sqmk0"
  GOOGLE_GENAI_API_KEY: "AIzaSyDtZM50zvt0m9TBZZc0ijbgBnR7t9sqmk0"
  GRC_GEMINI__API_KEY: "AIzaSyDtZM50zvt0m9TBZZc0ijbgBnR7t9sqmk0"
