apiVersion: v1
kind: Service
metadata:
  name: grc-gateway
  labels:
    app.kubernetes.io/name: grc-gateway
    app.kubernetes.io/part-of: grc
    app.kubernetes.io/component: gateway
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: grc-gateway
  ports:
    - name: http
      port: 8095
      targetPort: http
